[pip]
index-url = 'https://mirrors.aliyun.com/pypi/simple/'
extra-index-url = 'https://pypi.tuna.tsinghua.edu.cn/simple/\nhttps://pypi.mirros.ustc.edu.cn/simple/\nhttps://mirrors.cloud.tencent.com/pypi/simple/\nhttps://pypi.org/simple/'